pde_name: "1D_Burgers"
model_name: "PINO"
if_training: True
continue_training: False
model_path: null          # path of checkpoint
output_dir: "./checkpoint/"
save_period: 20
training_type: "single"   # or autoregressive
initial_step: 1           # always 1 in origin implementation, but more is ok  
epochs: 500
seed : 0

model:
  width : 32
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  fc_dim: 128
  act: 'gelu'
  in_channels : 1   # input
  out_channels : 1   # output

train:
  scenario : "1D_Burgers"
  scheduler_gamma: 0.5
  ic_loss: 2.0
  f_loss: 1.0
  xy_loss: 10.0
  save_name : "1d_burgers_256_41_2x"

################################################################

dataset:
  name : "Burgers"
  single_file: True
  file_name: "1D_Burgers_Sols_Nu0.001.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 8 
  reduced_resolution_t: 5
  reduced_resolution_pde: 4
  reduced_resolution_pde_t: 5
  reduced_batch: 1
  test_ratio: 0.1
  if_grid_norm : False
# dataloader args
dataloader:
  batch_size: 50
  num_workers: 1
  pin_memory: False
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5
