model_name: 'PINN'
scenario: 'darcy2d'

pde: '2dDarcy'
model_update: 500
filename: '2D_DarcyFlow_beta0.01_Train.hdf5'
epochs: 25000
input_ch: 4
output_ch: 1
learning_rate: 1.e-3
root_path: '/home/data2/fluidbench/2D/DarcyFlow/'
val_num: 1
if_periodic_bc: True
period: 5000
val_time: 1.0
val_batch_idx: 9000
aux_params: [0.01]
seed: '9000'

# test
model_path: '/home/hechangye/PDEBench-main/pdebench/models/2D_DarcyFlow_beta0.01_Train.hdf5_9000_PINN.pt-25000.pt'

dataset:
 reduced_resolution: 4
 reduced_resolution_t: 5