model_name: 'PINN'
scenario: 'CFD2D'

pde: '2dCFD'
model_update: 500
filename: '2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5'
epochs: 25000
input_ch: 3
output_ch: 4
learning_rate: 1.e-3
root_path: '/home/data2/fluidbench/2D/CFD/2D_Train_Rand/'
val_num: 1
if_periodic_bc: True
period: 5000
val_time: 1.0
val_batch_idx: 9000
aux_params: [1.6666666667]
seed: '9000'

# test
model_path: '/home/hechangye/PDEBench-main/pdebench/models/2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5_9000_PINN.pt-25000.pt'

dataset:
 reduced_resolution: 4
 reduced_resolution_t: 5