model_name: 'PINN'
scenario: 'pde1D'

pde: '1dCH'
model_update: 500
filename: '1D_Cahn-Hilliard_10e-6_0.01.hdf5'
epochs: 25000
input_ch: 2
output_ch: 1
learning_rate: 1.e-3
root_path: '/home/data2/fluidbench/1D/Cahn-Hilliard/'
val_num: 1
if_periodic_bc: True
period: 5000
val_time: 1.0
val_batch_idx: 9000
aux_params: [10e-6, 0.01]
seed: '0000'

# test
model_path: '/home/hechangye/PDEBench-main/pdebench/models/1D_Cahn-Hilliard_10e-6_0.01.hdf5_9000_PINN.pt-25000.pt'

dataset:
 reduced_resolution: 4
 reduced_resolution_t: 5