pangu:
    experiment_name: "onescience-Launch-Dev"
    experiment_desc: "onescience launch development"
    run_desc: "Pangu ERA5 Training"
    
    channels:  ['10m_u_component_of_wind_0', '10m_v_component_of_wind_0', '2m_temperature_0', 'mean_sea_level_pressure_0', 
                
                'geopotential_1000', 'geopotential_925', 'geopotential_850', 'geopotential_700', 'geopotential_600', 'geopotential_500', 
                'geopotential_400', 'geopotential_300', 'geopotential_250', 'geopotential_200', 'geopotential_150', 'geopotential_100', 'geopotential_50',
                
                'specific_humidity_1000', 'specific_humidity_925', 'specific_humidity_850', 'specific_humidity_700', 'specific_humidity_600',
                'specific_humidity_500', 'specific_humidity_400', 'specific_humidity_300', 'specific_humidity_250', 'specific_humidity_200', 
                'specific_humidity_150', 'specific_humidity_100', 'specific_humidity_50', 
                
                'temperature_1000', 'temperature_925', 'temperature_850', 'temperature_700', 'temperature_600', 'temperature_500', 'temperature_400', 
                'temperature_300', 'temperature_250', 'temperature_200','temperature_150', 'temperature_100', 'temperature_50', 
                
                'u_component_of_wind_1000', 'u_component_of_wind_925', 'u_component_of_wind_850', 'u_component_of_wind_700', 'u_component_of_wind_600', 
                'u_component_of_wind_500', 'u_component_of_wind_400', 'u_component_of_wind_300', 'u_component_of_wind_250', 'u_component_of_wind_200', 
                'u_component_of_wind_150', 'u_component_of_wind_100', 'u_component_of_wind_50', 
                
                'v_component_of_wind_1000', 'v_component_of_wind_925', 'v_component_of_wind_850', 'v_component_of_wind_700', 'v_component_of_wind_600', 
                'v_component_of_wind_500', 'v_component_of_wind_400', 'v_component_of_wind_300', 'v_component_of_wind_250', 'v_component_of_wind_200', 
                'v_component_of_wind_150', 'v_component_of_wind_100', 'v_component_of_wind_50'
                ]
    
    
    
    start_epoch: 0
    max_epoch: 1000
    img_size: [721, 1440]
    patch_size: [2, 4, 4]
    embed_dim: 192
    num_heads: [6, 12, 12, 6]
    window_size: [2, 6, 12]
    num_samples_per_year: None
    num_steps: 1
    stats_dir: "/work/home/onescience2025/osdatasets/pangu_weather/dataset/stats/"
    mask_dir: "/work/home/onescience2025/osdatasets/pangu_weather/dataset/static/"
    checkpoint_dir : "/work/home/onescience2025/osmodels/pangu_weather/checkpoints"
    mask_dtype: "float32"
    batch_size: 1
    num_workers: 1
    patience: 50

    train_data_dir: "/work/home/onescience2025/osdatasets/pangu_weather/dataset/train/"
    val_data_dir: "/work/home/onescience2025/osdatasets/pangu_weather/dataset/val/"
    test_data_dir: "/work/home/onescience2025/osdatasets/pangu_weather/dataset/test/"
    

      


