hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/

# data configs
data_dir: ../raw_dataset/cylinder_flow/cylinder_flow

ckpt_path: "../checkpoints"

# training configs
num_input_features: 6
num_output_features: 3
num_edge_features: 3

# performance configs
use_apex: True
amp: False
jit: False
num_dataloader_workers: 4
do_concat_trick: False
num_processor_checkpoint_segments: 0
recompute_activation: False

# test & visualization configs
num_test_samples: 10
num_test_time_steps: 300
viz_vars: ["u", "v", "p"]
frame_skip: 10
frame_interval: 1
