defaults:
  - /logging/python: default
  - override hydra/job_logging: disabled  # We use rank-aware logger configuration instead.
  - _self_

hydra:
  run:
    dir: ${output}
  output_subdir: hydra  # Default is .hydra which causes files not being uploaded in W&B.

# Dimensionality of the problem (2D or 3D).
dim: 2

# Main output directory.
output: outputs

# The directory to search for checkpoints to continue training.
resume_dir: ${output}

# The dataset directory must be set either in command line or config.
data:
  data_dir: ???
  num_history: 5
  num_node_types: 6
  train:
    split: train
  valid:
    split: valid
  test:
    split: test

# The loss should be set in the experiment.
loss: ???

# The optimizer should be set in the experiment.
optimizer: ???

# The scheduler should be set in the experiment.
lr_scheduler: ???

train:
  batch_size: 20
  epochs: 100
  checkpoint_save_freq: 5
  dataloader:
    batch_size: ${..batch_size}
    shuffle: true
    num_workers: 2
    pin_memory: true
    drop_last: true

test:
  batch_size: 1
  device: cuda
  dataloader:
    batch_size: ${..batch_size}
    shuffle: false
    num_workers: 1
    pin_memory: true
    drop_last: false

compile:
  enabled: false
  args:
    backend: inductor

amp:
  enabled: false

loggers:
  wandb:
    _target_: loggers.WandBLogger
    project: meshgraphnet
    entity: onescience
    name: l-mgn
    group: l-mgn
    mode: disabled
    dir: ${output}
    id:
    wandb_key:
    watch_model: false
  tensorboard:
    _target_: loggers.TensorBoardLogger
    log_dir: ${output}/tensorboard

inference:
  frame_skip: 1
  frame_interval: 1
