hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/

# data configs
data_dir: /data/Water-3D
dim: 3

# model config
activation: "silu"

# training configs
batch_size: 2
epochs: 100
num_training_samples: 1000 # 400
num_training_time_steps: 300 # 600 - 5 (history)
lr: 1e-4
lr_min: 1e-6
lr_decay_rate: 0.999 # every 10 epoch decays to 35%
num_input_features: 30 # 3 (pos) + 3*5 (history of velocity) + 6 boundary features + 6 (node type)
num_output_features: 3 # 2 acceleration
num_edge_features: 4 # 2 displacement + 1 distance
processor_size: 8
radius: 0.035
dt: 0.005

# performance configs
use_apex: True
amp: False
jit: False
num_dataloader_workers: 4 # 4
do_concat_trick: False
num_processor_checkpoint_segments: 0
recompute_activation: False

# wandb configs
wandb_mode: offline
watch_model: False
wandb_key:
wandb_project: "meshgraphnet"
wandb_entity:
wandb_name:
ckpt_path: "./checkpoints_3d"

# test & visualization configs
num_test_samples: 1
num_test_time_steps: 400
frame_skip: 1
frame_interval: 1
