hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/

# data configs
data_dir: /data/Water
dim: 2

# model config
activation: "silu"

# training configs
batch_size: 20
epochs: 100
num_training_samples: 1000 # 400
num_training_time_steps: 990 # 600 - 5 (history)
lr: 1e-4
lr_min: 1e-6
lr_decay_rate: 0.999 # every 10 epoch decays to 35%
num_input_features: 22 # 2 (pos) + 2*5 (history of velocity) + 4 boundary features + 6 (node type)
num_output_features: 2 # 2 acceleration
num_edge_features: 3 # 2 displacement + 1 distance
processor_size: 8
radius: 0.015
dt: 0.0025

# performance configs
use_apex: True
amp: False
jit: False
num_dataloader_workers: 10 # 4
do_concat_trick: False
num_processor_checkpoint_segments: 0
recompute_activation: False

# wandb configs
wandb_mode: offline
watch_model: False
wandb_key:
wandb_project: "meshgraphnet"
wandb_entity:
wandb_name:
ckpt_path: "./checkpoints_2d"

# test & visualization configs
num_test_samples: 1
num_test_time_steps: 200
frame_skip: 1
frame_interval: 1
