pde_name: "2D_Black-Scholes-Barenblatt"
model_name: "FNO"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
# training args
seed: 0
training_type: "autoregressive"
t_train: 101
initial_step: 10
unroll_step: 20
epochs: 500
# dataset args 
dataset:
  single_file: True
  file_name: "2D_Black-Scholes-Barenblatt_r0.05_sigma0.4.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader args
dataloader:
  batch_size: 4
  num_workers: 4
  pin_memory: False
# model args
model:
  num_channels: 1
  modes: 12
  width: 20
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5