pde_name: "3D_Maxwell"
model_name: "FNO"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
# training args
seed: 0
training_type: "autoregressive"
t_train: 8
initial_step: 2
unroll_step: 20
epochs: 500
# dataset args 
dataset:
  single_file: False
  file_name: "3D_Maxwell_10_1.h5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader args
dataloader:
  batch_size: 2
  num_workers: 1
  pin_memory: False
# model args
model:
  num_channels: 6
  modes: 12
  width: 20
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5