pde_name: "2D_Compressible_NS"
model_name: "PINO"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 10
seed: 0
training_type: "single"   # or autoregressive
initial_step: 1
epochs: 200

model:
  width : 64
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: 'gelu'
  in_channels : 4   # input
  out_channels : 4   # output

train:
  scenario : "2D_Compressible_NS"
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 0.5
  xy_loss: 10.0
  save_name : "2d_CFD_4x_init1"


dataset:
  name : "2D_Compressible_NS"
  single_file: True
  file_name: "2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 4
  reduced_resolution_t: 1
  reduced_resolution_pde: 1
  reduced_resolution_pde_t: 1
  reduced_batch: 1
  test_ratio: 0.1
  if_grid_norm : False
# dataloader args
dataloader:
  batch_size: 1 # 8
  num_workers: 0
  pin_memory: False
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler args 
scheduler:
  name: "StepLR"
  step_size: 50
  gamma: 0.5
