pde_name: "1D_diffusion_sorption"
model_name: "DeepONet"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
seed: 0
initial_step: 1
epochs: 500

model:
  input_ize: 256
  act: 'tanh'
  in_channels : 1   # input
  out_channels : 1   # output
  query_dim: 2
  base_model: "MLP"
train:
  scenario : "1D_diffusion_sorption"
  save_name : "1d_diff-sorp_256_100"
  training_type: "single"   # or autoregressive

dataset:
  name : "1D_diffusion_sorption"
  single_file: False
  file_name: "1D_diff-sorp_NA_NA.h5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 4
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader args
dataloader:
  batch_size: 50
  num_workers: 1
  pin_memory: False
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5
