# Hyperparameters
hp:
    training_duration: 200000000
    # Training duration based on the number of processed samples
    total_batch_size: 8 # 256
    # Total batch size
    batch_size_per_gpu: 1 # 2
    # Batch size per GPU
    lr: 0.0002
    # Learning rate
    grad_clip_threshold: null
    # no gradient clipping for defualt non-patch-based training
    lr_decay: 1
    # LR decay rate
    lr_rampup: 10000000
    # Rampup for learning rate, in number of samples

# Performance
perf:
    fp_optimizations: amp-fp16  #  fp32 会报显存不足
    # Floating point mode, one of ["fp32", "fp16", "amp-fp16", "amp-bf16"]
    # "amp-{fp16,bf16}" activates Automatic Mixed Precision (AMP) with {float16,bfloat16}
    dataloader_workers: 4
    # DataLoader worker processes
    songunet_checkpoint_level: 0 # 0 means no checkpointing
    # Gradient checkpointing level, value is number of layers to checkpoint

# I/O
io:
    print_progress_freq: 5 # 1000
    # How often to print progress
    save_checkpoint_freq: 5000
    # How often to save the checkpoints, measured in number of processed samples
    validation_freq: 5000
    # how often to record the validation loss, measured in number of processed samples
    validation_steps: 10
    # how many loss evaluations are used to compute the validation loss per checkpoint 
