hydra:
  job:
    chdir: true
    name: regression  # choose from [regression, diffusion, patched_diffusion]
  run:
    dir: ./outputs/${hydra:job.name}
 
# Get defaults
defaults:

  # Dataset
  - dataset/cwb_train

  # Model
  - model/corrdiff_regression
  #- model/corrdiff_diffusion
  #- model/corrdiff_patched_diffusion

  # Training
  - training/corrdiff_regression
  #- training/corrdiff_diffusion
  #- training/corrdiff_patched_diffusion

  # Validation (comment out to disable validation)
  - validation/cwb
