hydra:
  job:
    chdir: True
  run:
    dir: ./outputs/

train_dir: ./hdf5_tas_data1/train
validation_dir: ./hdf5_tas_data1/test
stats_dir: ./hdf5_tas_data1/statss

ckpt_path: ./checkpoints
channels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

num_steps_train: 1
num_steps_validation: 8

wb_artifacts: False
use_mlflow: True

start_epoch: 0
max_epoch: 80

num_samples_per_year_train: 1456
num_samples_per_year_validation: 4
num_workers_train: 8
num_workers_validation: 8

batch_size_train: 2
batch_size_validation: 1
