# PDE Info
pde_name: "1D_Burgers"
temporal_domain: (0, 2)
resolution_t: 201
spatial_domain: "[(-1, 1)]"
resolution: [1024]
variables: {"nu": 0.001}
num_outputs: 1
# training args
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
tensorboard: True
log_dir: "./logs/tensorboard/"
seed: 0
time_window: 10
neighbors: 3
unrolling: 1
unroll_step: 20
epochs: 500
# datasets args
dataset:
  single_file: True
  file_name: "1D_Burgers_Sols_Nu0.001.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 4
  reduced_resolution_t: 5
  reduced_batch: 1
  test_ratio: 0.1
# dataloader args
dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: True
# model args
model_name: "MPNN"
model:
  hidden_features: 128
  hidden_layer: 6
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-4
  weight_decay: 1.e-8
# learning rate schedule
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5