# PDE Information
pde_name: "2D_Allen-Cahn"
temporal_domain: (0, 1)
resolution_t: 101
spatial_domain: "[(0, 1), (0, 1)]"
resolution: [128, 128]
variables: {"c1": 0.0001, "c2": 1}
num_outputs: 1
# training args
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
tensorboard: True
log_dir: "./logs/tensorboard/"
seed: 0
time_window: 10
neighbors: 1 # create graph
unrolling: 1
unroll_step: 20
epochs: 500
# datasets args
dataset:
  single_file: True
  file_name: "2D_Allen-Cahn_0.0001_1.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 2
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader args
dataloader:
  batch_size: 8
  num_workers: 1
  pin_memory: True
# model args
model_name: "MPNN"
model:
  hidden_features: 128
  hidden_layer: 6
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-4
  weight_decay: 1.e-8
# learning rate schedule
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5