pde_name: "2D_Compressible_NS"
model_name: "DeepONet"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 10
seed: 0   
initial_step: 1
epochs: 200

model:
  input_size: 128
  act: 'tanh'
  in_channels : 4   # input
  out_channels : 4   # output
  query_dim: 3
  base_model: "MLP"
train:
  scenario : "2D_Compressible_NS"
  save_name : "2d_CFD_128"
  training_type: "single"

dataset:
  name : "2D_Compressible_NS"
  single_file: True
  file_name: "2D_CFD_Rand_M0.1_Eta0.1_Zeta0.1_periodic_128_Train.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader args
dataloader:
  batch_size: 50
  num_workers: 1
  pin_memory: True
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 50
  gamma: 0.5
