pde_name: "2D_DarcyFlow"
model_name: "DeepONet"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
seed: 0
initial_step: 1
epochs: 500

model:
  input_size: 128
  act: 'tanh'
  in_channels : 1   # input
  out_channels : 1   # output
  query_dim: 2
  base_model: "MLP"
train:
  scenario : "2D_DarcyFlow"
  save_name : "2d_darcy_128"
  training_type: "autoregressive" 

dataset:
  name : "2D_DarcyFlow"
  single_file: True
  file_name: "2D_DarcyFlow_beta1.0_Train.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
  test_ratio: 0.1
# dataloader args
dataloader:
  batch_size: 50
  num_workers: 1
  pin_memory: False
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay : 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5
