afno_backbone:
  name: 'Oceancast'

  nettype: 'afno'
  num_blocks: 3
  depth: 6
  chunks: 4
  block_partition: [1,1,1,1,1,1]
  patch_size: 4
  image_width: 160
  image_height: 360
  width: 56
  modes: 32
  target: 'default' 
  # If you want to train the model for forecasting wave, using following types
  
  input_types: [ 'Wind_Sin','Wind_Cos', 'Wind_Strength',
                 'Wind_Sin_Forecast','Wind_Cos_Forecast', 'Wind_Strength_Forecast',
                 'Wave_Period','Wave_Height', 'Wave_Direction' ]
  output_types: [ 'Wave_Period','Wave_Height', 'Wave_Direction' ]

  in_channels: [ 0,  1,  2,  3,  4,  5,  6,  7, 
                 8,  9, 10, 11, 12, 13, 14, 15, 
                 16, 17, 18, 19, 20, 21, 22, 23,
                 24, 25, 26, 27, 28, 29, 30, 31,
                 32, 33, 34, 35, 36, 37, 38, 39,
                 40, 41, 42, 43, 44, 45, 46, 47,
                 48, 49, 50, 51, 52, 53, 54, 55,
                 56, 57, 58, 59, 60, 61, 62, 63, 
                 64, 65, 66, 67, 68, 69, 70, 71 ]
  N_in_channels: 72
  
  out_channels: [ 48, 49, 50, 51, 52, 53, 54, 55, 
                  56, 57, 58, 59, 60, 61, 62, 63, 
                  64, 65, 66, 67, 68, 69, 70, 71 ]
  N_out_channels: 24
    
  # If you want to train the model for sea surface parameters, using following types
  
  # input_types: [ 'Wind_Sin','Wind_Cos', 'Wind_Strength',
  #                'Wind_Sin_Forecast','Wind_Cos_Forecast', 'Wind_Strength_Forecast',
  #                'Ocean_SST','Ocean_SSH', 'Ocean_SSS' ]
  # output_types: [ 'Ocean_SST','Ocean_SSH', 'Ocean_SSS' ]  
  # in_channels: [ 0,  1,  2,  3,  4,  5,  6,  7, 
  #                8,  9, 10, 11, 12, 13, 14, 15, 
  #                16, 17, 18, 19, 20, 21, 22, 23,
  #                24, 25, 26, 27, 28, 29, 30, 31,
  #                32, 33, 34, 35, 36, 37, 38, 39,
  #                40, 41, 42, 43, 44, 45, 46, 47,
  #                48, 49, 50, 51, 52, 53, 54, 55,
  #                56, 57, 58, 59, 60, 61, 62, 63, 
  #                64, 65, 66, 67, 68, 69, 70, 71 ]
  # N_in_channels: 72
  
  # out_channels: [ 48, 49, 50, 51, 52, 53, 54, 55, 
  #                 56, 57, 58, 59, 60, 61, 62, 63, 
  #                 64, 65, 66, 67, 68, 69, 70, 71 ]
  # N_out_channels: 24

    # If you want to train the model for ocean currents, using following types
  
  # input_types: [ 'Wind_Sin','Wind_Cos', 'Wind_Strength',
  #                'Wind_Sin_Forecast','Wind_Cos_Forecast', 'Wind_Strength_Forecast',
  #                'Current_EastWard', 'Current_NorthWard']
  # output_types: [ 'Current_EastWard', 'Current_NorthWard' ] 

  # in_channels: [   0,  1,  2,  3,  4,  5,  6, 
  #                  7,  8,  9, 10, 11, 12, 13, 
  #                 14, 15, 16, 17, 18, 19, 20, 
  #                 21, 22, 23, 24, 25, 26, 27, 
  #                 28, 29, 30, 31, 32, 33, 34,
  #                 35, 36, 37, 38, 39, 40, 41, 
  #                 42, 43, 44, 45, 46, 47, 48, 
  #                 49, 50, 51, 52, 53, 54, 55]
  # N_in_channels: 35
  
  # out_channels: [ 21, 22, 23, 24, 25, 26, 27, 
  #                 28, 29, 30, 31, 32, 33, 34]
  # N_out_channels: 14

  
  
  normalization: 'zscore'  
  enable_nhwc: !!bool False
  optimizer_type: 'FusedAdam'
  add_noise: !!bool False
  noise_std: 0

  count_data_path: './data/Wind_Sin'
  ocean_data_path: '/public/SothisAI/sharingCenter/data/easyscience/Ocean/' # '/public/home/dqren/raindata/Ocean' 
  wind_data_path: './data/'
  current_data_path: '/public/SothisAI/sharingCenter/data/easyscience/Ocean/'
  global_means_path: './means_stds'
  global_stds_path:  './means_stds'
  maskpath: './WaveMask.pt'
  model_path: 'checkpoint/weight'

  loss: 'l2'
  lr: 5E-5
  scheduler: 'CosineAnnealingLR'
  num_data_workers: 4
  dt: 8  # how many timesteps ahead the model will predict
  n_history: 8  # how many previous timesteps to consider
  infer_steps: 7
  prediction_type: 'iterative'
  ics_type: "default"
  save_raw_forecasts: !!bool True
  save_channel: !!bool False
  masked_acc: !!bool False
  perturb: !!bool False
  max_epochs: 10000
  patience: 50
  batch_size: 5
  T_max: 50
  two_step_training: !!bool False
  plot_animations: !!bool False
  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True
