model_name: 'PINN'
scenario: 'Max3D'

pde: '3dMax'
model_update: 500
filename: '3D_Maxwell_10_1.h5'
epochs: 25000
input_ch: 4
output_ch: 6
learning_rate: 1.e-3
root_path: '/home/data2/PDEData/3D/Maxwell/'
val_num: 1
if_periodic_bc: True
period: 5000
val_time: 1.0
val_batch_idx: 900
aux_params: [0.0001, 1.0]
seed: '900'

# test
model_path: '/home/hechangye/PDEBench-main/pdebench/models/3D_Maxwell_10_1.h5_9000_PINN.pt-25000.pt'

dataset:
 reduced_resolution: 4
 reduced_resolution_t: 5