model_name: 'PINN'
scenario: 'pde1D'

# pde: '1dDiff-react'
# pde: '1dAdv'
pde: '1dBgs'

model_update: 500
# filename: 'ReacDiff_Nu0.5_Rho1.0.hdf5'
# filename: '1D_Advection_Sols_beta0.1.hdf5'
filename: '1D_Burgers_Sols_Nu0.001.hdf5'
epochs: 25000
input_ch: 2
output_ch: 1
learning_rate: 1.e-3
# root_path: '/home/data2/PDEData/1D/ReactionDiffusion/'
# root_path: '/home/data2/PDEData/1D/Advection/'
root_path: '/home/data2/PDEData/1D/Burgers/Train/'
val_num: 1

# ReacDiff_Nu0.5_Rho1.0.hdf5
# 1D_Advection_Sols_beta0.1.hdf5
# 1D_Burgers_Sols_Nu0.001
if_periodic_bc: True 

period: 5000
val_time: 2.0
val_batch_idx: 9000
# aux_params: [0.5, 1.0] # ReacDiff
# aux_params: [0.1] # Advection
aux_params: [0.001] # burgers

# unused
seed: '0000'


# model_path: '/home/hechangye/PDEBench-main/pdebench/models/ReacDiff_Nu0.5_Rho1.0.hdf59000_PINN.pt-25000.pt'
# model_path: '/home/hechangye/PDEBench-main/pdebench/models/1D_Advection_Sols_beta0.1.hdf59000_PINN.pt-25000.pt'
model_path: '/home/hechangye/PDEBench-main/pdebench/models/1D_Burgers_Sols_Nu0.001.hdf5_9000_PINN.pt-25000.pt'

dataset:
 reduced_resolution: 4
 reduced_resolution_t: 5
