model_name: 'PINN'
scenario: 'BS2d'

pde: '2dBS'
model_update: 500
filename: '2D_Black-Scholes-Barenblatt_r0.05_sigma0.4.hdf5'
epochs: 25000
input_ch: 3
output_ch: 1
learning_rate: 1.e-3
root_path: '/home/data2/PDEData/2D/Black-Scholes-Barenblatt/'
val_num: 1
if_periodic_bc: True
period: 5000
val_time: 1.0
val_batch_idx: 900
aux_params: [0.0001, 1.0]
seed: '900'

# test
model_path: '/home/hechangye/PDEBench-main/pdebench/models/2D_Black-Scholes-Barenblatt_r0.05_sigma0.4.hdf5_9000_PINN.pt-25000.pt'

dataset:
 reduced_resolution: 4
 reduced_resolution_t: 5