pde_name: "2D_Burgers"
model_name: "UNO"
if_training: True
continue_training: False
model_path: null
output_dir: "./checkpoint/"
save_period: 20
# training args
seed: 0
training_type: "autoregressive"
t_train: 101
initial_step: 10
unroll_step: 20
epochs: 500
# dataset args
dataset:
  single_file: False
  file_name: "2D_Burgers_Nu0.001.hdf5"
  saved_folder: YOUR_DATASET_DIR_PATH
  reduced_resolution: 1
  reduced_resolution_t: 1
  reduced_batch: 1
# dataloader args
dataloader:
  batch_size: 8
  num_workers: 2
  pin_memory: False
# model args
model:
  num_channels: 2
  width: 30
# optimizer args
optimizer:
  name: 'Adam'
  lr: 1.e-3
  weight_decay: 1.e-4
# scheduler args
scheduler:
  name: "StepLR"
  step_size: 100
  gamma: 0.5