- dataset_prefix: /work/home/onescience2025/biao.liu/release-onescience/onescience/examples/biosciences/evo2/data/data_evo2_612/chr20_21_22_uint8_distinct_byte-level_train
  dataset_split: train
  dataset_weight: 1.0
- dataset_prefix: /work/home/onescience2025/biao.liu/release-onescience/onescience/examples/biosciences/evo2/data/data_evo2_612/chr20_21_22_uint8_distinct_byte-level_val
  dataset_split: validation
  dataset_weight: 1.0
- dataset_prefix: /work/home/onescience2025/biao.liu/release-onescience/onescience/examples/biosciences/evo2/data/data_evo2_612/chr20_21_22_uint8_distinct_byte-level_test
  dataset_split: test
  dataset_weight: 1.0